### ISSUE TITLE
role="list-box" is not valid

### ISSUE THREAD

**Issue by kawarimidoll** [ntnyq/vuepress-plugin-social-share#26]
I’d be glad if you would use "listbox" instead of "list-box" in SocialShare.vue.

When I used this plugin, Audits(google chrome)  flagged ARIA roles with invalid value "list-box".
"listbox" is valid value.
ref: https://www.w3.org/TR/wai-aria-1.1/#role_definitions , https://www.w3.org/TR/wai-aria-1.1/#listbox

Thank you,

**Comment by ntnyq** [comment]
Thanks for your feedback.

It's been fixed in the latest publish.

**Comment by kawarimidoll** [comment]
Thank you for the fix!
