### ISSUE TITLE
can't overide the defaults through "extendsNetworks"

### ISSUE THREAD

**Issue by trolologuy** [ntnyq/vuepress-plugin-social-share#28]
Hello,

### Using:
- vuepress/1.4.1 
- darwin-x64 
- node-v13.11.0

## Issue:
I can't override the default Networks settings.
What I'm trying to achieve is to change the "sharer" links (both in the global social share as in the "social-share" element, to put my own social media links instead.

What am I doing wrong? / Is this indeed a bug in the plugin?

### I'm using the following code:
__/docs/README.md__
```
# hello-world

<social-share
  :networks="[
    'facebook', 'email',
    is-plain
  ]"
/>

```

__/docs/.vuepress/config.js__ :
```
const extendsNetworks = {
  email: {
    sharer: 'mailto:myfancymail@github.com',
    type: 'popup',
    isPlain: true,
  },
  facebook: {
    sharer: 'https://google.com',
    type: 'popup',
    isPlain: true,
  },
}

  module.exports = {
    plugins: [
      '@vuepress/plugin-nprogress',
      '@vuepress/plugin-back-to-top',
      'social-share',
        {
          networks: ['twitter', 'facebook', 'reddit', 'telegram'],
          isPlain: true,
          extendsNetworks,
        },
    ]
}
```

### Installing and running by doing:
```
yarn global add vuepress 
yarn add vuepress-plugin-social-share -D
vuepress dev        
```

**Comment by ntnyq** [comment]
Check [Guide - extendsnetworks](https://sns.goyfe.com/guide/#extendsnetworks)
You need to set `type: true` so it would open a sharer in current window rather than opening a new browser tab.
