### ISSUE TITLE
Development environment running error

### ISSUE THREAD

**Issue by classfang** [ntnyq/vuepress-plugin-social-share#75]
Uncaught (in promise) Error: usePageFrontmatter() is called without provider.

![WX20230908-101128@2x](https://github.com/ntnyq/vuepress-plugin-social-share/assets/27616248/4c324fd7-a1c4-460d-8aee-f0687224caba)

**Comment by ntnyq** [comment]
See context in https://github.com/vuepress/vuepress-next/issues/885

The reason why peer deps are pinned https://github.com/vuepress/vuepress-next/issues/1195

Just released [a new version](https://github.com/ntnyq/vuepress-plugin-social-share/releases/tag/v2.0.0-beta.17) to support  vuepress@v2.0.0-beta.67.

Let me know if you still face any issue.

**Comment by classfang** [comment]
The problem has been resolved, thank you
